### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by MatthewScholefield** [feathersjs-ecosystem/feathers-chat-react#4]
Hi, I noticed there's no license. I know there's not much code in the repo, but it would be helpful to have.

**Comment by MatthewScholefield** [comment]
@daffl Mentioning since it looks like you're the sole contributor.

**Comment by cirosantilli** [comment]
Matthew, BTW, did you manage to signup/login? :cold_sweat: https://github.com/feathersjs-ecosystem/feathers-chat-react/issues/5
