### ISSUE TITLE
How to signup/login

### ISSUE THREAD

**Issue by cirosantilli** [feathersjs-ecosystem/feathers-chat-react#5]
Hi David,

I'm trying out several web stacks for a new project, and this looked real promising, but I couldn't login, am I doing anything obviously wrong?

```
git clone https://github.com/feathersjs-ecosystem/feathers-chat-react
cd feathers-chat-react
git checkout 36d56cbe80bbd5596f6a108b1de9db343b33dac3
npm install -g yarn
yarn install
yarn start
```

The server starts, I visit http://localhost:3000/ , I see the "Log in or signup" page, but clicking the buttons doesn't seem to do anything.

Ubuntu 20.10, Node.js v14.15.3, yarn@1.22.10, Chromium 85, Firefox 86.

**Comment by MatthewScholefield** [comment]
It works fine for me. Make sure you are running the [feathers-chat api](https://github.com/feathersjs/feathers-chat) on port 3030 (the default for that repo). You can check the network requests to see if anything is wrong. If the server is not running you would probably see CORS failures in the console.

**Comment by cirosantilli** [comment]
Ops you gotta run https://github.com/feathersjs/feathers-chat first, then it works.

**Comment by cirosantilli** [comment]
(simultaneous comment oh yeah)
